### ISSUE TITLE
rake git:changelog results in undefined method `<<' for nil:NilClass

### ISSUE THREAD

**Issue by zdavatz** [jbarnette/hoe-git#2]
Hi

I love your plugin for Git! rake git:manifest saved my day!

But: when I run 

rake git:changelog

I get this error (with --trace).

undefined method `<<' for nil:NilClass

./lib/hoe/git.rb:57:in `define_git_tasks'

./lib/hoe/git.rb:51:in `map'

./lib/hoe/git.rb:51:in `define_git_tasks'

/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in `call'

/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in `execute'

/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in `each'

/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in `execute'

/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:597:in `invoke_with_call_chain'

/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'

/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'

/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:583:in `invoke'

/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2051:in `invoke_task'

/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'

/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `each'

/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'

/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in 
`standard_exception_handling'

/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2023:in `top_level'

/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2001:in `run'

/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in 
`standard_exception_handling'

/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1998:in `run'

/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/bin/rake:31

/usr/bin/rake:19:in `load'

/usr/bin/rake:19

Any hints how to fix that?

Best
Zeno

**Comment by jbarnette** [comment]
Eep, that's no good. At first glance it feels like fragile handling of some sort of text parse: I'll take a look at the code when I have a sec this afternoon.

**Comment by zdavatz** [comment]
Thank you soo much. An I will take a look at the new commit tomorrow morning ;)

**Comment by zdavatz** [comment]
Interesting. I just tried it on another project of mine and there it worked!

**Comment by zenspider** [comment]
No repro steps.

I just overhauled git:changelog completely so I'm closing this. reopen if the problem still exists and you can provide repro steps.
