### ISSUE TITLE
Is there a way to ignore this warning: Won't release: Dirty index or untracked files present!

### ISSUE THREAD

**Issue by zdavatz** [jbarnette/hoe-git#3]
Hi

Is there a way to ignore this warning and still push/release the gem?

Won't release: Dirty index or untracked files present!

Would be nice because sometime you want to release a gem for testing as well, without committing any code for the moment. Would be nice if the user could skip that test.

Best
Zeno

**Comment by zenspider** [comment]
No. There is no way to ignore that "warning". It goes against all sane process and we won't support that workflow.
